apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "mtls-bookinfo"
  namespace: "bookinfo"
spec:
  peers:
  - mtls: {}
  targets:
  - name: details
  - name: reviews
  - name: ratings
  ports:
  - number: 9080